<?php

namespace App\Filament\Resources\ProductVariations\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ProductVariationInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('product.name')
                    ->label('Product'),
                TextEntry::make('product_woocommerce_id')
                    ->numeric(),
                TextEntry::make('woocommerce_id')
                    ->numeric(),
                TextEntry::make('permalink')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('description')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('status')
                    ->placeholder('-'),
                TextEntry::make('menu_order')
                    ->numeric(),
                TextEntry::make('sku')
                    ->label('SKU')
                    ->placeholder('-'),
                TextEntry::make('price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('regular_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('sale_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_from')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_from_gmt')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_to')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_to_gmt')
                    ->dateTime()
                    ->placeholder('-'),
                IconEntry::make('on_sale')
                    ->boolean(),
                IconEntry::make('purchasable')
                    ->boolean(),
                IconEntry::make('virtual')
                    ->boolean(),
                IconEntry::make('downloadable')
                    ->boolean(),
                TextEntry::make('download_limit')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('download_expiry')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('tax_status')
                    ->placeholder('-'),
                TextEntry::make('tax_class')
                    ->placeholder('-'),
                IconEntry::make('manage_stock')
                    ->boolean(),
                TextEntry::make('stock_quantity')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('stock_status')
                    ->placeholder('-'),
                TextEntry::make('backorders')
                    ->placeholder('-'),
                IconEntry::make('backordered')
                    ->boolean(),
                IconEntry::make('visible')
                    ->boolean(),
                IconEntry::make('shipping_required')
                    ->boolean(),
                IconEntry::make('shipping_taxable')
                    ->boolean(),
                TextEntry::make('weight')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('shipping_class')
                    ->placeholder('-'),
                TextEntry::make('shipping_class_id')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('price_html')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('date_created')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_created_gmt')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_modified')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_modified_gmt')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
