<?php

namespace App\Filament\Resources\Products\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ProductInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('woocommerce_id')
                    ->numeric(),
                TextEntry::make('slug')
                    ->placeholder('-'),
                TextEntry::make('permalink')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('type')
                    ->placeholder('-'),
                TextEntry::make('status')
                    ->placeholder('-'),
                IconEntry::make('featured')
                    ->boolean(),
                TextEntry::make('catalog_visibility')
                    ->placeholder('-'),
                TextEntry::make('sku')
                    ->label('SKU')
                    ->placeholder('-'),
                TextEntry::make('price')
                    ->money()
                    ->placeholder('-'),
                TextEntry::make('regular_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('sale_price')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_from')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_from_gmt')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_to')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_on_sale_to_gmt')
                    ->dateTime()
                    ->placeholder('-'),
                IconEntry::make('on_sale')
                    ->boolean(),
                TextEntry::make('total_sales')
                    ->numeric(),
                IconEntry::make('virtual')
                    ->boolean(),
                IconEntry::make('downloadable')
                    ->boolean(),
                TextEntry::make('download_limit')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('download_expiry')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('external_url')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('button_text')
                    ->placeholder('-'),
                TextEntry::make('tax_status')
                    ->placeholder('-'),
                TextEntry::make('tax_class')
                    ->placeholder('-'),
                IconEntry::make('manage_stock')
                    ->boolean(),
                TextEntry::make('stock_quantity')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('stock_status')
                    ->placeholder('-'),
                TextEntry::make('backorders')
                    ->placeholder('-'),
                IconEntry::make('backorders_allowed')
                    ->boolean(),
                IconEntry::make('backordered')
                    ->boolean(),
                TextEntry::make('low_stock_amount')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('sold_individually')
                    ->boolean(),
                TextEntry::make('weight')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('shipping_required')
                    ->boolean(),
                IconEntry::make('shipping_taxable')
                    ->boolean(),
                TextEntry::make('shipping_class')
                    ->placeholder('-'),
                TextEntry::make('shipping_class_id')
                    ->numeric()
                    ->placeholder('-'),
                IconEntry::make('reviews_allowed')
                    ->boolean(),
                TextEntry::make('average_rating')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('rating_count')
                    ->numeric(),
                TextEntry::make('parent.name')
                    ->label('Parent')
                    ->placeholder('-'),
                TextEntry::make('purchase_note')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('menu_order')
                    ->numeric(),
                TextEntry::make('price_html')
                    ->placeholder('-')
                    ->columnSpanFull(),
                IconEntry::make('has_options')
                    ->boolean(),
                TextEntry::make('date_created')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_created_gmt')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_modified')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('date_modified_gmt')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
